ckpt: lightning_logs/version_0/best_checkpoint.ckpt
context_length: 64
dataset: double_well
device: cuda:0
diffusion_config: diffusion_small_config
freq: H
init_skip: False
num_samples: 1
prediction_length: 1000
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 4
setup: forecasting
use_features: False
use_lags: False #true
normalization: true
use_validation_set: False
