train:
  epochs: 1000
  batch_size: 64
  lr: 0.001
  itr_per_epoch: 128
  prediction_length: 100
  context_length: 100
  num_of_samples: 1000
  val_size: 9000
  test_size: 3000
  valid_epoch_interval: 50
  stride: 5
  training_curv: "checkpoints_100_100/csdi_with_early_stopping_50/alanine_psi"
  normalization: "none"
  
diffusion:
  layers: 4
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50 
  schedule: "quad"
  is_linear: True

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "test"
  normalization: "none" 
  num_sample_features: 1