data:
  data_path: "training_data/double_well_std.npz"
  L: 100
  H: 100
  train_stride: 25 #stride for trainign the encoder
  val_stride: 25       
  retrieval_stride: 25 #==train_stride #stride for creating references must be equal to train_stride
                        #because the encoder would output embeddings for windows it has never seen

model:
  input_size: 1
  output_size: 100 #20 must match L
  num_channels: [32, 64, 32]      # much smaller
  kernel_size: 3
  dropout: 0.2
  use_reference: True
  k: 3

train:
  device: "cuda:0"
  batch_size: 256 #128                   
  learning_rate: 0.001
  epochs: 200
  grad_clip: 1.0
  num_workers: 1                   
  print_every: 10
  val_start: 200 ##index of time step where val start

path:
  dataset_path: "training_data/double_well_std.npz"
  encoder_path: "tcn_weights/tcn_encoder_dw.pth"
  vec_path: "references/double_well/embeddings.pt"
  futures_path: "references/double_well/futures.npy"
  ref_path: "references/double_well/indices.pt"
  training_curv: "tcn_weights/dw_loss.npz"