data:
  train_data: "DATA/linear_gaussian_train.npz"
  test_data: "DATA/linear_gaussian_test.npz"
  L: 100
  H: 100
  train_stride: 5 
  val_stride: 5       
  retrieval_stride: 5 #50 #10
  train_test_split: 800 ##only used in embedding training context

model:
  input_size: 1
  output_size: 100 # must match L
  num_channels: [4, 4, 4]      # much smaller
  kernel_size: 3
  dropout: 0.2
  use_reference: True
  k: 3

train:
  device: "cuda:0"
  batch_size: 128                 
  learning_rate: 0.001 #0.0001
  epochs: 1000
  grad_clip: 1.0
  num_workers: 1                   
  print_every: 10
  val_start: 800 ##includex context
  train_size: 5000


path:
  encoder_path: "checkpoints/tcn/linear_gaussian.pth"
  vec_path: "references/linear_gaussian/embeddings.pt"
  futures_path: "references/linear_gaussian/futures.npy"
  ref_path: "references/linear_gaussian/indices.pt"
  training_curv: "checkpoints/tcn/linear_gaussian_loss.npz"