context_length: 100
prediction_length: 100
stride: 25
test_size: 3000
val_size: 9000

train_curv: "checkpoints/nsdiff/double_well/"

epochs: 1000
batch_size: 64
lr: 0.0001
patience: 20
valid_epoch_interval: 50
num_of_samples: 500

normalization: "none"

diffusion_steps: 100
beta_schedule: "linear"
beta_start: 0.0001
beta_end: 0.5

d_model: 16 #32 #512     
n_heads: 2 #4      
e_layers: 2 #2     
d_layers: 1 #1
d_ff: 16 #32 #64 #128    
moving_avg: 25
factor: 3
distil: true
dropout: 0.05
activation: "gelu"

rolling_length: 50 #100 #observed past for var estimator

k_z: 0.01
k_cond: 1 ##highe conditionaing??
d_z: 6 #8
CART_input_x_embed_dim: 16 #32
p_hidden_layers: 2