ckpt: checkpoints/tsdiff/alanine_psi/lightning_logs/version_0/best_checkpoint.ckpt
model: unconditional
freq: H
context_length: 100
prediction_length: 100
diffusion_config: diffusion_small_config
use_features: False
use_lags: False
init_skip: False
batch_size: 64
normalization: none
device: cuda:0
setup: forecasting
dataset: alanine_psi
num_samples: 500
sampler: ddpm
sampler_params:
  guidance: MSE
  scale: 2
eval_every: 50