path:
  test_data: "DATA/alanine_psi_test.npz"
  train_data: "DATA/alanine_psi_train.npz"
  encoder_path: "checkpoints/tcn/alanine_psi.pth"
  futures_path: "references/alanine_psi/futures.npy"
  ref_path: "references/alanine_psi/indices.pt"

retrieval:
  L: 100
  H: 100
  stride: 5 #for training RATD  must be tcn confg data.train_stride
  k: 3
  device: "cuda:0"

model:
  timeemb: 128
  featureemb: 16
  is_unconditional: false
  target_strategy: "test"
  use_reference: True
  num_sample_features: 1

diffusion:
  num_steps: 50
  beta_start: 0.0001
  beta_end: 0.5
  schedule: "quad"
  ref_size: 100 
  h_size: 100        
  channels: 64
  diffusion_embedding_dim: 128
  nheads: 8
  layers: 4
  is_linear: True 

train:
  L: 100
  H: 100
  device: "cuda:0"
  batch_size: 64
  learning_rate: 1.0e-3
  epochs: 1000
  milestones: [60, 85]
  gamma: 0.1
  grad_clip: 1.0
  num_workers: 2
  print_every: 10
  val_start: 800 #200 #includes the context 
  val_every: 50 ##run evaluation every 50 
  path: "checkpoints/ratd/alanine_psi"
  stride: 20 ##must match retreival_stride in tcn config
  train_size: 9000

forecast:
  test_size: 3000
  out_path: "results/ratd/alanine_psi.npz"
  n_samples: 500