train:
  epochs: 600
  batch_size: 64
  lr: 0.001
  itr_per_epoch: 128
  prediction_length : 100
  context_length: 100
  num_of_samples: 100
  validation_size: 2000
  testing_size: 3000
  valid_epoch_interval: 50
  stride: 50
  training_curv: "checkpoints/csdi/double_well/loss.npz"


diffusion:
  layers: 6 #4
  channels: 128 #64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.02
  num_steps: 400
  schedule: "linear" #"quad"
  is_linear: True

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "test"
  normalization: "none" 
  num_sample_features: 1